# Generated by Django 2.2 on 2019-06-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip'),
        ),
    ]
